// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
import { AUTH_TYPE } from "aws-appsync/lib/link/auth-link";

const awsmobile =  {
    "aws_appsync_graphqlEndpoint": "https://7u5h7yto5rhrpeat4tp2lsm5i4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY" as AUTH_TYPE,
    "aws_appsync_apiKey": "da2-cnkoe5e64nftvabegwzykpdtoe",
};

export default awsmobile;
